#/usr/bin/env python
from matcher import match_title_to_sonarr_episode, match_title_to_sonarr_show

titles = [
    "Jet Lag: The Game :: Ep 2 — We Played Hide And Seek Across NYC",
    "Distractible Podcast :: Dippy Dawg Does Dunkirk",
    "Vivziepop :: HELLUVA BOSS - SINSMAS // S2: Episode 12 -FINALE",
    "First We Feast :: Saquon Barkley Hurdles Over Spicy Wings | Hot Ones"
]

sonarr_data = [
{'series': 'Hot Ones', 'season': 0, 'episode': 1, 'title': "Sean Evans and Chili Klaus Eat the Carolina Reaper, the World's Hottest Chili Pepper"},
{'series': 'Hot Ones', 'season': 0, 'episode': 2, 'title': 'Sean Evans Answers Hot Ones Questions from Fans'},
{'series': 'Hot Ones', 'season': 0, 'episode': 3, 'title': "Chili Klaus and Sean Evans Eat the World's Hottest Pepper on the Carriage Ride From Hell"},
{'series': 'Hot Ones', 'season': 0, 'episode': 4, 'title': "World's Hottest Chip Challenge"},
{'series': 'Hot Ones', 'season': 0, 'episode': 5, 'title': 'Hot Sauce Shopping at Heatonist'},
{'series': 'Hot Ones', 'season': 0, 'episode': 6, 'title': 'Tony Hawk Eats Spicy Wings LIVE at ComplexCon'},
{'series': 'Hot Ones', 'season': 0, 'episode': 7, 'title': 'Hot Ones LIVE Trivia with Super Fans at ComplexCon'},
{'series': 'Hot Ones', 'season': 0, 'episode': 8, 'title': 'Action Bronson Eating Wings in Reverse'},
{'series': 'Hot Ones', 'season': 0, 'episode': 9, 'title': 'The Hot Ones Holiday Special'},
{'series': 'Hot Ones', 'season': 0, 'episode': 10, 'title': 'Hot Ones Mailbag: Sean Evans Answers Fan Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 11, 'title': "Rhett & Link Eat the World's Spiciest Curry with Sean Evans"},
{'series': 'Hot Ones', 'season': 0, 'episode': 12, 'title': 'Neil deGrasse Tyson Drops Knowledge | Hot Ones Extras'},
{'series': 'Hot Ones', 'season': 0, 'episode': 13, 'title': 'Season Four Hot Sauce Lineup, REVEALED'},
{'series': 'Hot Ones', 'season': 0, 'episode': 14, 'title': 'The Hot Ones Doughnut Is a Buffalo Wing in Pastry Form'},
{'series': 'Hot Ones', 'season': 0, 'episode': 15, 'title': "Stephen Does A 'Hot Ones' Interview With Sean Evans"},
{'series': 'Hot Ones', 'season': 0, 'episode': 16, 'title': 'Sean Evans Goes to The Late Show With Stephen Colbert'},
{'series': 'Hot Ones', 'season': 0, 'episode': 17, 'title': 'Everything You Need to Know About The Last Dab, the Hottest Sauce on Hot Ones'},
{'series': 'Hot Ones', 'season': 0, 'episode': 18, 'title': 'How to Eat a Chicken Wing | Hot Ones Extra'},
{'series': 'Hot Ones', 'season': 0, 'episode': 19, 'title': 'How to Pair Hot Sauce with Food | Hot Ones Extra'},
{'series': 'Hot Ones', 'season': 0, 'episode': 20, 'title': 'A Very Spicy Holiday Special'},
{'series': 'Hot Ones', 'season': 0, 'episode': 21, 'title': 'Season Five Hot Sauce Lineup REVEALED'},
{'series': 'Hot Ones', 'season': 0, 'episode': 22, 'title': 'How to Make Hot Sauce | Hot Ones Extra'},
{'series': 'Hot Ones', 'season': 0, 'episode': 23, 'title': 'Machine Gun Kelly Has a Rematch with the Wings of Death | Hot Ones Throwback'},
{'series': 'Hot Ones', 'season': 0, 'episode': 24, 'title': 'Sean Evans Answers Spicy Fan Questions and Shares Season 5 Highlights'},
{'series': 'Hot Ones', 'season': 0, 'episode': 25, 'title': 'Season 6 Hot Sauce Lineup, REVEALED'},
{'series': 'Hot Ones', 'season': 0, 'episode': 26, 'title': 'Sean Evans Answers Fans Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 27, 'title': 'Kevin Hart and Tiffany Haddish Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 28, 'title': 'Sean Evans Reveals the Season 7 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 29, 'title': 'The Hot Ones Holiday Special'},
{'series': 'Hot Ones', 'season': 0, 'episode': 30, 'title': 'Rae Sremmurd Plays Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 31, 'title': "Sean's Gordon Ramsay Nightmare"},
{'series': 'Hot Ones', 'season': 0, 'episode': 32, 'title': 'Sean Evans Reveals the Season 8 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 33, 'title': "LEGO Sean Evans Interviews Queen Watevra Wa'Nabi"},
{'series': 'Hot Ones', 'season': 0, 'episode': 34, 'title': 'Tom Segura and Bert Kreischer Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 35, 'title': 'Sean Evans Tackles Season 8 Controversies and Answers Fan Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 36, 'title': 'Seth Rogen and Charlize Theron Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 37, 'title': 'Sean Evans Reveals the Season 9 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 38, 'title': "Stranger Things' Caleb McLaughlin and Gaten Matarazzo Play Truth or Dab"},
{'series': 'Hot Ones', 'season': 0, 'episode': 39, 'title': 'Sean Evans Answers Burning Fan Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 40, 'title': 'Marques Brownlee and Casey Neistat Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 41, 'title': 'Jay Pharoah Channels Keanu Reeves While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 42, 'title': 'Sean Evans Reveals the Season 10 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 43, 'title': 'The Hot Ones Holiday Special 2019'},
{'series': 'Hot Ones', 'season': 0, 'episode': 44, 'title': 'Diplo and Dillon Francis Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 45, 'title': 'The Best Da Bomb Reactions of 2019'},
{'series': 'Hot Ones', 'season': 0, 'episode': 46, 'title': 'Skip Bayless and Shannon Sharpe Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 47, 'title': 'Sean Evans Reveals the Season 11 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 48, 'title': 'Noah Centineo and Lana Condor Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 49, 'title': 'Quarantine Update'},
{'series': 'Hot Ones', 'season': 0, 'episode': 50, 'title': 'The Bella Twins Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 51, 'title': 'Bert Kreischer Returns For A Rematch Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 52, 'title': 'Sean Evans Answers Fan Questions and Addresses Season 11 Controversies'},
{'series': 'Hot Ones', 'season': 0, 'episode': 53, 'title': 'The Best of Sean Evans Answering Questions from Celebrities'},
{'series': 'Hot Ones', 'season': 0, 'episode': 54, 'title': 'Sean Evans Tells the Story of the Time a SWAT Team Raided His Apartment'},
{'series': 'Hot Ones', 'season': 0, 'episode': 55, 'title': 'Sean Evans Shares His Spookiest Ghost Story'},
{'series': 'Hot Ones', 'season': 0, 'episode': 56, 'title': 'Sean Calls His Dad to Fact-Check A Childhood Injury'},
{'series': 'Hot Ones', 'season': 0, 'episode': 57, 'title': 'Sean Evans Describes His First Kiss'},
{'series': 'Hot Ones', 'season': 0, 'episode': 58, 'title': 'Sean Evans Reveals the Season 12 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 59, 'title': 'How to Play Truth or Dab at Home'},
{'series': 'Hot Ones', 'season': 0, 'episode': 60, 'title': 'Sean Evans Answers Fan Questions and Addresses the Biggest Challenge of Season 12'},
{'series': 'Hot Ones', 'season': 0, 'episode': 61, 'title': 'Karrueche Tran and Victor Cruz Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 62, 'title': 'Anthony Joshua and Israel Adesanya Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 63, 'title': 'Lil Yachty and Sean Evans Eat the Spiciest Chip in the World'},
{'series': 'Hot Ones', 'season': 0, 'episode': 64, 'title': 'Sean Evans Reveals the Season 13 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 65, 'title': 'The Hot Ones Holiday Special 2020'},
{'series': 'Hot Ones', 'season': 0, 'episode': 66, 'title': 'Cody Ko and Noel Miller Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 67, 'title': 'The Best Da Bomb Reactions of 2020'},
{'series': 'Hot Ones', 'season': 0, 'episode': 68, 'title': 'The Best Last Dab Reactions of All Time'},
{'series': 'Hot Ones', 'season': 0, 'episode': 69, 'title': 'Sean Evans Reveals the Season 14 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 70, 'title': 'Sean Evans Gets Schooled on the Carolina Reaper by Smokin’ Ed Currie'},
{'series': 'Hot Ones', 'season': 0, 'episode': 71, 'title': 'Matty Matheson and Benny Blanco Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 72, 'title': 'Keke Palmer Listens to the Devil While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 73, 'title': 'Sean Evans Reveals the Season 15 Hot Sauce Lineup—Plus, a BIG Announcement!'},
{'series': 'Hot Ones', 'season': 0, 'episode': 74, 'title': 'Sean Evans Tackles Season 15 Controversies and Answers Fan Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 75, 'title': 'Sean Evans and Sasha Banks Try the Paqui One Chip Challenge'},
{'series': 'Hot Ones', 'season': 0, 'episode': 76, 'title': 'Ben Platt and Amandla Stenberg Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 77, 'title': 'Steve-O and Wee-Man Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 78, 'title': 'Sean Evans Reveals the Season 16 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 79, 'title': 'Coach Brad Underwood Gets Full Court Pressed By Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 80, 'title': 'Gordon Ramsay Returns for the Hot Ones Holiday Extravaganza'},
{'series': 'Hot Ones', 'season': 0, 'episode': 81, 'title': 'The Best Da Bomb Reactions of 2021'},
{'series': 'Hot Ones', 'season': 0, 'episode': 82, 'title': 'The Best Last Dab Reactions of 2021'},
{'series': 'Hot Ones', 'season': 0, 'episode': 83, 'title': 'Sean Evans Reveals the Season 17 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 84, 'title': 'NFL Pros Gabriel Davis and Isaiah Mckenzie Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 85, 'title': 'Goldberg and Big E Want to Fight While Playing Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 86, 'title': 'Sean Evans Answers Fan Questions'},
{'series': 'Hot Ones', 'season': 0, 'episode': 87, 'title': 'Food Network Stars Alex Guarnaschelli and Eric Adjepong Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 88, 'title': 'Sean Evans Reveals the Season 18 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 89, 'title': 'The Ultimate Sean Evans Interview'},
{'series': 'Hot Ones', 'season': 0, 'episode': 90, 'title': 'The Impractical Jokers Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 91, 'title': 'Tony Hawk and Sean Evans Take on the Paqui One Chip Challenge'},
{'series': 'Hot Ones', 'season': 0, 'episode': 92, 'title': 'Sean Evans Taste-Tests the New Hot Ones x Shake Shack Menu'},
{'series': 'Hot Ones', 'season': 0, 'episode': 93, 'title': 'Sean Evans Reveals the Season 19 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 94, 'title': 'Puss in Boots Can’t Feel His Tail While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 95, 'title': 'Will Ferrell Brings the Spirit to the Hot Ones Holiday Extravaganza'},
{'series': 'Hot Ones', 'season': 0, 'episode': 96, 'title': 'The Best Da Bomb Reactions of 2022'},
{'series': 'Hot Ones', 'season': 0, 'episode': 97, 'title': 'The Best Last Dab Reactions of 2022'},
{'series': 'Hot Ones', 'season': 0, 'episode': 98, 'title': 'Sean Evans Reveals the Season 20 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 99, 'title': 'NFL Pros Darius Slayton and Andrew Thomas Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 100, 'title': 'A History of Hot Ones Guests Yelling at Sean Evans'},
{'series': 'Hot Ones', 'season': 0, 'episode': 101, 'title': 'Hot Ones Classics: Bert Kreischer Relives His First Encounter with the Wings of Death'},
{'series': 'Hot Ones', 'season': 0, 'episode': 102, 'title': 'The Chainsmokers Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 0, 'episode': 103, 'title': 'Sean Evans Reveals the Season 21 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 104, 'title': 'J.R. Smith and Richard Jefferson Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 1, 'episode': 1, 'title': "Tony Yayo Talks Shmoney Dance & Eminem's Taco Habit While Eating Spicy Chicken Wings"},
{'series': 'Hot Ones', 'season': 1, 'episode': 2, 'title': 'Anthony Rizzo On Chicago Cubs Rivalries & Baseball Superstitions While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 3, 'title': 'Machine Gun Kelly Talks Diddy, Hangovers, & Amber Rose While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 4, 'title': 'Gunplay Talks Rick Ross, Wingstop, and X-Box Live Fights While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 5, 'title': 'Ja Rules Talks 50 Cent Beef, Jail Recipes, and Media Stereotypes While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 6, 'title': 'B.o.B Talks Eggplant Fridays, Kid Rock, and Snapchat While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 7, 'title': 'Prince Amukamara Talks NFL Salaries & Pre-Game Sex While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 1, 'episode': 8, 'title': 'DJ Khaled Talks Fuccbois, Finga Licking, and Media Dinosaurs While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 1, 'title': 'Curren$y Talks Munchies, Industry Games, and Rap Dogs While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 2, 'title': "Tinashe Talks NFL Dances and 2015's Sexiest Songs While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 2, 'episode': 3, 'title': 'Tommy Chong Talks Weed, Bernie Sanders, and Smoking with Snoop While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 4, 'title': 'T.J. Miller Talks Deadpool, Hecklers, and Relationship Advice While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 5, 'title': 'Coolio Talks Hip-Hop Cooking and "Gangsta\'s Paradise" Folklore While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 6, 'title': 'Joey Fatone Talks *NSYNC, DJ Khaled, and Guy Fieri While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 7, 'title': 'Michael Rapaport Talks LeBron James, Phife Dawg, & Reality TV While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 8, 'title': 'Key & Peele Lose Their Minds Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 9, 'title': 'Riff Raff Goes Full Burly Boy on Some Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 10, 'title': 'Eddie Huang Gets Destroyed by Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 11, 'title': "Chris D'Elia Turns Into DJ Khaled While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 2, 'episode': 12, 'title': 'Mike Epps Gets Crushed by Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 13, 'title': 'Jim Gaffigan Rediscovers His Flop Sweat Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 14, 'title': 'Carly Aquilino Takes on the Spicy Wings Challenge'},
{'series': 'Hot Ones', 'season': 2, 'episode': 15, 'title': 'Redman Wilds Out Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 16, 'title': 'Rob Gronkowski Gets Blindsided by Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 17, 'title': 'Rob Corddry Cries Real Tears Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 18, 'title': 'Jeff Ross Gets Roasted by Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 19, 'title': 'David Cross Embraces the Extremes of Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 20, 'title': 'Eric Andre Turns Into Tay Zonday While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 21, 'title': 'Joe Budden Keeps It Real While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 22, 'title': 'Matty Matheson Turns Into a Motivational Speaker Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 23, 'title': 'RZA and Paul Banks Tag Team Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 24, 'title': 'Bert Kreischer Sweats Profusely Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 25, 'title': 'YG Keeps His Cool Eating Spicy Nuggets'},
{'series': 'Hot Ones', 'season': 2, 'episode': 26, 'title': 'Jay Pharoah Has a Staring Contest While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 27, 'title': 'Harley Morenstein Has His Worst Day of 2016 Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 28, 'title': 'Travis Kelce Gets Woozy Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 29, 'title': 'Hasan Minhaj Has an Out-of-Body Experience Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 30, 'title': 'Kevin Hart Catches a High Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 31, 'title': 'Martin Garrix Tests His Limits Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 32, 'title': 'Bobby Lee Has an Accident Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 33, 'title': 'Action Bronson Blows His High Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 34, 'title': 'T-Pain Has a Tongue Seizure Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 35, 'title': 'Rachael Ray Mainlines Hot Sauce for Thanksgiving'},
{'series': 'Hot Ones', 'season': 2, 'episode': 36, 'title': 'Tom Colicchio Goes Full Top Chef on Some Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 37, 'title': 'Post Malone Sauces on Everyone While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 38, 'title': 'N.O.R.E. Gets Wasted While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 2, 'episode': 39, 'title': 'James Franco and Bryan Cranston Bond Over Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 1, 'title': 'Padma Lakshmi Gracefully Destroys Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 2, 'title': 'Joey "CoCo" Diaz Breaks Out the Blue Cheese While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 3, 'title': 'Danny Brown Has An Orgasm Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 4, 'title': 'Ricky Gervais Pits His Mild British Palate Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 5, 'title': 'Charlie Day Learns to Love Ridiculously Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 6, 'title': 'Mac DeMarco Tries to Stay Chill While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 7, 'title': 'Russell Brand Achieves Enlightenment While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 8, 'title': 'Charlie Sloth Makes His Mum Proud Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 9, 'title': 'Kyle Kinane Gets Angry Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 10, 'title': 'Dax Shepard Does Mental Math While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 11, 'title': 'H3H3 Productions Does Couples Therapy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 12, 'title': 'Keke Palmer Laughs Uncontrollably While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 13, 'title': 'Charlamagne Tha God Gets Heated Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 14, 'title': 'DJ Snake Reveals His Human Side While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 15, 'title': 'Guy Fieri Becomes the Mayor of Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 16, 'title': 'Kevin Love Gets Dunked On By Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 17, 'title': 'Neil deGrasse Tyson Explains the Universe While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 18, 'title': 'Thomas Middleditch Does Improv While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 19, 'title': 'Andy Cohen Spills the Tea While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 20, 'title': 'Tom Arnold Melts Down While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 21, 'title': 'Coyote Peterson Gets STUNG by Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 22, 'title': 'Nick Kroll Delivers a PSA While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 23, 'title': 'Superfan Brett Baker Grills Sean Evans Over Spicy Wings'},
{'series': 'Hot Ones', 'season': 3, 'episode': 24, 'title': 'Seth Rogen and Dominic Cooper Suffer While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 1, 'title': 'Cara Delevingne Shows Her Hot Sauce Balls While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 2, 'title': 'Liam Payne Gets Cocky Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 3, 'title': 'Steve-O Tells Insane Stories While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 4, 'title': 'Vince Staples Delivers Hot Takes While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 5, 'title': 'Adam Richman Fanboys Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 6, 'title': 'ASAP Ferg Harlem Shakes While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 7, 'title': 'Kevin Durant Sweats It Out Over Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 8, 'title': 'Henry Rollins Channels His Anger at Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 9, 'title': 'Dillon Francis Hurts His Body with Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 10, 'title': 'Joji Sets His Face on Fire While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 11, 'title': 'Wanda Sykes Confesses Everything While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 12, 'title': 'Terry Crews Hallucinates While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 13, 'title': 'Gary Vaynerchuk Tests His Mental Toughness While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 14, 'title': 'Artie Lange Is Raw and Uncensored While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 15, 'title': 'Chris Jericho Gets Body Slammed by Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 16, 'title': 'Gabrielle Union Impersonates DMX While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 17, 'title': 'Wale Battles Spicy Wings LIVE'},
{'series': 'Hot Ones', 'season': 4, 'episode': 18, 'title': 'Bob Saget Hiccups Uncontrollably While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 19, 'title': 'Mario Batali Celebrates Thanksgiving with Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 20, 'title': 'Alexa Chung Fears for Her Life While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 21, 'title': "Logic Solves a Rubik's Cube While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 4, 'episode': 22, 'title': 'Casey Neistat Melts His Face Off While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 4, 'episode': 23, 'title': 'Chili Klaus Faces the Most Extreme Hot Ones Ever'},
{'series': 'Hot Ones', 'season': 5, 'episode': 1, 'title': 'Taraji P. Henson Needs a Stunt Double to Eat Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 2, 'title': 'Sasha Banks Bosses Up While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 3, 'title': 'Von Miller Geeks Out Over Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 4, 'title': 'Rich Brian Experiences Peak Bromance While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 5, 'title': 'Hannibal Buress Freestyles While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 6, 'title': 'Michael B. Jordan Gets Knocked Out By Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 7, 'title': 'Ty Burrell Fears Sudden Death While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 8, 'title': 'Charlize Theron Takes a Rorshach Test While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 9, 'title': 'Adam Rippon Competes in the Olympics of Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 10, 'title': 'Gabriel Iglesias Does Wrestling Trivia While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 11, 'title': 'Shawn Mendes Discovers a New Side of Himself While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 12, 'title': 'Philip DeFranco Sets a YouTube Record While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 13, 'title': 'Trick Daddy Prays for Help While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 14, 'title': 'Tyra Banks Cries For Her Mom While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 15, 'title': 'Alton Brown Rigorously Reviews Spicy Wings'},
{'series': 'Hot Ones', 'season': 5, 'episode': 16, 'title': 'John Mayer Has a Sing-Off While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 1, 'title': 'Johnny Knoxville Gets Smoked By Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 2, 'title': 'Natalie Portman Pirouettes in Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 3, 'title': 'Marques Brownlee Ranks Hot Sauce Labels While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 4, 'title': 'Joel Embiid Trusts the Process While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 5, 'title': 'Tom Segura Tears Up While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 6, 'title': 'Joji and Rich Brian Play the Newlywed Game While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 7, 'title': 'Wiz Khalifa Gets Smoked Out By Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 8, 'title': 'Al Roker Gets Hit by a Heat Wave of Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 9, 'title': 'Michael Cera Experiences Mouth Pains While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 10, 'title': 'Issa Rae Raps While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 11, 'title': 'Rhett & Link Hiccup Uncontrollably While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 12, 'title': 'Jeff Goldblum Says He Likes to Be Called Daddy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 6, 'episode': 13, 'title': 'Eddie Huang Seeks Revenge Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 1, 'title': 'Chrissy Teigen Gets Drunk on Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 2, 'title': 'Tenacious D Gets Rocked By Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 3, 'title': 'Anderson .Paak Sings Hot Sauce Ballads While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 4, 'title': 'Adam Carolla Rants Like a Pro While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 5, 'title': 'Lil Yachty Has His First Experience With Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 6, 'title': 'E-40 Asks a Fan to Save Him While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 7, 'title': 'Lilly Singh Fears for Her Life While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 8, 'title': 'Blake Griffin Gets Full-Court Pressed By Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 9, 'title': 'Bill Burr Gets Red in the Face While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 10, 'title': 'Pete Holmes Does Improv While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 11, 'title': 'Vanessa Hudgens Does Tongue Twisters While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 7, 'episode': 12, 'title': '"Weird Al" Yankovic Goes Beyond Insanity While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 1, 'title': 'Gordon Ramsay Savagely Critiques Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 2, 'title': 'Abbi and Ilana of Broad City Go Numb While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 3, 'title': 'Seth Meyers Unravels While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 4, 'title': 'Ken Jeong Performs a Physical While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 5, 'title': 'Desus and Mero Get Smacked By Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 6, 'title': 'Offset Screams Like Ric Flair While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 7, 'title': 'Billie Eilish Freaks Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 8, 'title': 'Shaq Tries to Not Make a Face While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 9, 'title': 'Theo Von Fights the Dark Arts While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 10, 'title': 'Jimmy Butler Goes Rocky Balboa on Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 11, 'title': 'Chelsea Handler Goes Off the Rails While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 8, 'episode': 12, 'title': 'Scarlett Johansson Tries To Not Spoil Avengers While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 1, 'title': 'The Jonas Brothers Burn Up While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 2, 'title': 'Halle Berry Refuses to Lose to Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 3, 'title': 'Trevor Noah Rides a Pain Rollercoaster While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 4, 'title': 'Aubrey Plaza Snorts Milk While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 5, 'title': 'Schoolboy Q Learns to Respect Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 6, 'title': 'Adam Devine Gets Patriotic While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 7, 'title': 'Kumail Nanjiani Sweats Intensely While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 8, 'title': 'Binging with Babish Gets a Tattoo While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 9, 'title': 'Juice WRLD Eats Spicy Wings LIVE'},
{'series': 'Hot Ones', 'season': 9, 'episode': 10, 'title': 'Idris Elba Wants to Fight While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 11, 'title': 'Kristen Bell Ponders Morality While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 9, 'episode': 12, 'title': 'Stone Cold Steve Austin Puts the Stunner on Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 1, 'title': 'Shia LaBeouf Sheds a Tear While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 2, 'title': 'Ashton Kutcher Gets an Endorphin Rush While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 3, 'title': 'Noel Gallagher Looks Back in Anger at Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 4, 'title': 'Liza Koshy Meets Her Future Self While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 5, 'title': 'Paul Rudd Does a Historic Dab While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 6, 'title': 'Maisie Williams Shivers Uncontrollably While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 7, 'title': 'Nick Offerman Gets the Job Done While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 8, 'title': 'DaBaby Crushes Ice Cream While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 9, 'title': 'Kristen Stewart Brings the Angels to Eat Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 10, 'title': 'Chance The Rapper Battles Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 11, 'title': 'Brad Leone Celebrates Thanksgiving With Spicy Wings'},
{'series': 'Hot Ones', 'season': 10, 'episode': 12, 'title': 'John Boyega Summons the Force While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 1, 'title': 'Margot Robbie Pushes Her Limits While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 2, 'title': 'Zoë Kravitz Gets Trippy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 3, 'title': 'Will Ferrell Deeply Regrets Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 4, 'title': 'Halsey Experiences the Jersey Devil While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 5, 'title': 'Pete Davidson Drips With Sweat While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 6, 'title': 'David Dobrik Experiences Real Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 7, 'title': 'Big Sean Goes On a Spiritual Journey While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 8, 'title': 'Zac Efron Ups the Ante While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 11, 'episode': 9, 'title': 'Justin Timberlake Cries a River While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 1, 'title': 'Tom Segura Keeps It High and Tight While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 2, 'title': 'Brie Larson Takes On a New Form While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 3, 'title': 'Eric Andre Enters a Fugue State While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 4, 'title': 'Dan Levy Gets Panicky While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 5, 'title': 'Dua Lipa Sweats From Her Eyes While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 6, 'title': 'T-Pain Tastes Gas While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 7, 'title': 'Adam Richman Impersonates Noel Gallagher While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 8, 'title': 'Action Bronson Shakes It Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 9, 'title': 'Drew Barrymore Has a Hard Time Processing While Eating Hot Wings'},
{'series': 'Hot Ones', 'season': 12, 'episode': 10, 'title': 'Joseph Gordon-Levitt Gets Cocky While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 1, 'title': 'Jessica Alba Applies Lip Gloss While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 2, 'title': 'Ronda Rousey Splits Bones While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 3, 'title': 'Naomi Campbell Almost Faints While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 4, 'title': 'Matthew McConaughey Grunts it Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 5, 'title': 'Sam Smith Screams in Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 6, 'title': 'Saweetie Almost Tap Tap Taps Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 7, 'title': 'Thundercat Relives a Hot Sauce Nightmare While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 8, 'title': 'The Undertaker Takes Care of Business While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 13, 'episode': 9, 'title': 'Lil Nas X Celebrates Thanksgiving With the Biggest Last Dab Ever'},
{'series': 'Hot Ones', 'season': 13, 'episode': 10, 'title': 'Daniel Radcliffe Catches a Head Rush While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 1, 'title': 'Priyanka Chopra Jonas Explains the Essence of Hot Sauce While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 2, 'title': 'Dustin Poirier Is Paid in Full While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 3, 'title': 'Kevin James Forgets Who He Is While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 4, 'title': 'Awkwafina Gets Hot and Cold While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 5, 'title': 'Kenan Thompson Becomes a Card-Carrying Spiceman While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 6, 'title': 'Anthony Mackie Quotes Shakespeare While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 7, 'title': 'Paris Hilton Says "That\'s Hot" While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 8, 'title': 'Jennifer Garner Says “Golly” While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 9, 'title': 'J Balvin Meets the Devil While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 10, 'title': 'Jeffrey Dean Morgan Can’t Feel His Face While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 11, 'title': 'Russell Brand Serenades Superfan Brett Baker While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 14, 'episode': 12, 'title': 'Steve-O Takes It Too Far While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 1, 'title': 'Jack Harlow Returns to the Studio to Eat Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 2, 'title': 'Kamaru Usman Goes to the Mat Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 3, 'title': 'Quavo Is Stunned by Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 4, 'title': 'Elizabeth Olsen Feels Brave While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 5, 'title': 'Olivia Rodrigo Burns Her Lips While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 6, 'title': 'Malcolm Gladwell Hits the Tipping Point While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 7, 'title': 'Ed Sheeran Tries to Avoid Failure While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 8, 'title': 'David Harbour Feels Out of Control While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 9, 'title': 'Michael Che Gs Up While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 10, 'title': 'Lorde Drops the Mic While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 11, 'title': 'Matt Damon Sweats From His Scalp While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 15, 'episode': 12, 'title': 'Elijah Wood Tastes the Lava of Mount Doom While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 1, 'title': 'Jimmy Kimmel Feels Poisoned By Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 2, 'title': 'Derrick Lewis Is Not Okay While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 3, 'title': 'Jon Bernthal Gets Punished By Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 4, 'title': 'Megan Thee Stallion Turns Into Hot Girl Meg While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 5, 'title': 'CL Gets Extra Spicy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 6, 'title': 'Mila Kunis Hits the Ranch While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 7, 'title': 'Salma Hayek Adopts Sean Evans While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 8, 'title': 'Jeremy Renner Goes Blind in One Eye While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 9, 'title': 'David Chang Sweats Like Crazy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 10, 'title': 'Rob Lowe Ruins Thanksgiving By Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 11, 'title': 'Simu Liu Chugs Boba While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 16, 'episode': 12, 'title': 'Tom Holland Calls for a Doctor While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 1, 'title': 'Seth Rogen Scorches His Tongue While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 2, 'title': 'Tracee Ellis Ross Calls For Her Mommy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 3, 'title': 'Ed Helms Needs a Mouth Medic While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 4, 'title': 'Sebastian Stan Learns About Himself While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 5, 'title': 'Andrew Zimmern Has a Bucket List Moment While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 6, 'title': 'Dave Grohl Makes a New Friend While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 7, 'title': 'Colin Farrell Searches for Meaning in the Pain of Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 8, 'title': 'Courteney Cox Becomes Friends With Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 9, 'title': 'Jacob Elordi Feels Euphoric While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 10, 'title': 'Pusha T Has Beef With Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 11, 'title': 'Leslie Mann Gets Revenge While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 17, 'episode': 12, 'title': 'Josh Brolin Licks the Palate of Absurdity While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 1, 'title': 'Post Malone Has His Brain Hacked By Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 2, 'title': 'Millie Bobby Brown Needs a Milkshake While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 3, 'title': 'Queen Latifah Sets It Off While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 4, 'title': 'Kevin Bacon Needs Six Degrees of Separation From Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 5, 'title': 'Khloé Kardashian Holds Back Tears While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 6, 'title': 'Andrew Callaghan Goes For the Marrow While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 7, 'title': 'Tessa Thompson Feels Alive While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 8, 'title': 'Gabriel Iglesias Feels Cursed By Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 9, 'title': 'Daniel Kaluuya Listens to His Ego While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 10, 'title': 'Bear Grylls Battles For Survival Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 11, 'title': 'Mark Rober Gives Up on Science While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 12, 'title': 'Lizzo Earns Her Hot Sauce Crown While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 18, 'episode': 13, 'title': 'Neil Patrick Harris Needs Magic to Escape Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 1, 'title': 'David Blaine Does Magic While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 2, 'title': 'Kid Cudi Goes to the Moon While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 3, 'title': 'Viola Davis Gives a Master Class While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 4, 'title': 'Cole Bennett Needs Lemonade While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 5, 'title': "Cate Blanchett Pretends No One's Watching While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 19, 'episode': 6, 'title': 'Emma Chamberlain Has a Spiritual Awakening While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 7, 'title': 'James Corden Experiences Mouth Karma While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 8, 'title': 'Ramy Youssef Lives on a Prayer While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 9, 'title': 'Israel Adesanya Gives Thanks While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 10, 'title': 'Zoe Saldaña Gets Scorched By Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 11, 'title': 'Kate Hudson Stays Positive While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 12, 'title': 'Paul Dano Needs a Burp Cloth While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 19, 'episode': 13, 'title': 'Will Ferrell Brings the Spirit to the Hot Ones Holiday Extravaganza'},
{'series': 'Hot Ones', 'season': 20, 'episode': 1, 'title': 'Anna Kendrick Gets the Giggles While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 2, 'title': 'Bryan Cranston Fully Commits While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 3, 'title': 'Lenny Kravitz Stays Cool While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 4, 'title': 'Austin Butler Searches for Comfort While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 5, 'title': 'LL COOL J Needs Some Milk While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 6, 'title': 'Jenna Ortega Doesn’t Flinch While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 7, 'title': 'Pedro Pascal Cries From His Head While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 8, 'title': 'Niall Horan Gets the Shakes While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 9, 'title': 'Bob Odenkirk Has a Fire in His Belly While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 10, 'title': 'Florence Pugh Sweats From Her Eyebrows While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 11, 'title': 'Kieran Culkin Fires Sean While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 20, 'episode': 12, 'title': 'Jake Gyllenhaal Gets a Leg Cramp While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 1, 'title': 'Jason Sudeikis Embraces Da Bomb While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 2, 'title': 'Julia Louis-Dreyfus Fires Her Publicist While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 3, 'title': 'Marques Brownlee Short Circuits While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 4, 'title': "Rosalía Can't Stop Laughing While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 21, 'episode': 5, 'title': 'Melissa McCarthy Prepares For the Worst While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 6, 'title': 'Jennifer Lawrence Sobs in Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 7, 'title': 'John Mulaney Seeks the Truth While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 8, 'title': 'Lewis Capaldi Grasps for a Lifeline While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 9, 'title': 'Harry Kane Takes One For the Team While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 10, 'title': 'John Stamos Falls Out of His Chair While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 11, 'title': 'Stephen Curry Is On Fire While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 12, 'title': 'Anitta Lets It Fly While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 21, 'episode': 13, 'title': 'Gal Gadot Does a Spit Take While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 105, 'title': 'AEW Stars MJF and Adam Cole Play Truth or Dab (Bay Bay)'},
{'series': 'Hot Ones', 'season': 0, 'episode': 106, 'title': 'Mortal Kombat Co-Creator Ed Boon Feels Toasty While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 107, 'title': 'Sean Evans Reveals the Season 22 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 22, 'episode': 1, 'title': '*NSYNC Breaks Another Record While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 2, 'title': 'Cardi B Tries Not to Panic While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 3, 'title': 'Bobby Flay Throws Down Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 4, 'title': 'Doja Cat Is Doing Great While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 108, 'title': "Pepper X: Sean Evans, Chili Klaus & Smokin' Ed Currie Eat the New World's Hottest Pepper"},
{'series': 'Hot Ones', 'season': 22, 'episode': 5, 'title': 'Mick Foley Has an Inferno Match Against Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 6, 'title': 'Flea Is Red Hot While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 7, 'title': 'Tony Hawk Embraces the Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 8, 'title': 'Amelia Dimoldenberg Goes on a Date With Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 9, 'title': 'Louis Theroux Attacks the Shark While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 10, 'title': 'Carmelo Anthony Goes Hard in the Paint While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 11, 'title': 'Sebastian Maniscalco Is Thankful While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 12, 'title': 'Sterling K. Brown Performs Shakespeare While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 22, 'episode': 13, 'title': 'Mark Ruffalo Suffers For His Art While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 109, 'title': 'Steve-O Is Extra Naughty For the Hot Ones Holiday Extravaganza'},
{'series': 'Hot Ones', 'season': 0, 'episode': 110, 'title': 'The Best Da Bomb Reactions of 2023'},
{'series': 'Hot Ones', 'season': 0, 'episode': 111, 'title': 'The Best Last Dab Reactions of 2023'},
{'series': 'Hot Ones', 'season': 0, 'episode': 112, 'title': 'Sean Evans Reveals the Season 23 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 23, 'episode': 1, 'title': 'Sydney Sweeney Endures a Nightmare While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 2, 'title': 'John Oliver Fears For Humanity While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 3, 'title': 'Barry Keoghan Plays Hard to Get While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 113, 'title': 'Cam Newton and Brandon Marshall Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 23, 'episode': 4, 'title': 'Lil Dicky Spits Hot Fire While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 114, 'title': 'Gigi Hadid and Tan France Play Truth or Dab'},
{'series': 'Hot Ones', 'season': 23, 'episode': 5, 'title': 'Quinta Brunson Faces Her Fear of Hot Ones While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 6, 'title': 'Finn Wolfhard Embraces Insanity While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 7, 'title': 'Jamie Dornan Gets Punched in the Face by Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 8, 'title': 'Zayn Malik Lets the Tears Flow While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 115, 'title': 'Seth Rollins vs. Becky Lynch'},
{'series': 'Hot Ones', 'season': 0, 'episode': 116, 'title': 'Emma Chamberlain Goes for the Glory While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 9, 'title': 'Gwyneth Paltrow Is Full of Regret While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 10, 'title': 'Ice Spice Gets Melted By Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 117, 'title': 'Gabriel Iglesias vs. Emilio Rivera'},
{'series': 'Hot Ones', 'season': 0, 'episode': 118, 'title': 'Jalen Brunson vs. Josh Hart'},
{'series': 'Hot Ones', 'season': 0, 'episode': 119, 'title': 'Carlos Boozer vs. Jay Williams'},
{'series': 'Hot Ones', 'season': 23, 'episode': 11, 'title': 'Shakira Howls Like a She-Wolf While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 23, 'episode': 12, 'title': "Conan O'Brien Needs a Doctor While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 0, 'episode': 120, 'title': 'Zack Fox vs. Thundercat'},
{'series': 'Hot Ones', 'season': 0, 'episode': 121, 'title': 'Ludacris Gets Fired Up While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 122, 'title': 'mgk vs. Trippie Redd'},
{'series': 'Hot Ones', 'season': 0, 'episode': 123, 'title': 'Steve-O vs. Fiancée Lux Wright'},
{'series': 'Hot Ones', 'season': 0, 'episode': 124, 'title': 'Sean Evans Reveals the Season 24 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 24, 'episode': 1, 'title': 'Chris Hemsworth Gets Nervous While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 2, 'title': 'Lewis Hamilton Goes Full Send While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 3, 'title': "Will Smith Can't See While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 24, 'episode': 4, 'title': 'Shane Gillis Pounds Milk While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 5, 'title': 'Heidi Klum Strikes a Pose While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 125, 'title': 'The Boys’ Antony Starr vs. Chace Crawford'},
{'series': 'Hot Ones', 'season': 0, 'episode': 126, 'title': 'Sean Evans Interviews Himself While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 6, 'title': 'Lupita Nyong’o Feels Every Emotion While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 127, 'title': 'Uncle Roger vs. Nick DiGiovanni'},
{'series': 'Hot Ones', 'season': 0, 'episode': 128, 'title': 'Joey King vs. Miranda Cosgrove'},
{'series': 'Hot Ones', 'season': 24, 'episode': 7, 'title': 'Serena Williams Returns Hot Sauce Serve After Hot Sauce Serve While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 8, 'title': 'Sabrina Carpenter Talks Nonsense While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 129, 'title': 'Billie Eilish vs. Finneas'},
{'series': 'Hot Ones', 'season': 0, 'episode': 130, 'title': 'Glen Powell vs. Daisy Edgar-Jones'},
{'series': 'Hot Ones', 'season': 24, 'episode': 9, 'title': 'Childish Gambino Goes On a Vision Quest While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 10, 'title': 'Ryan Reynolds and Hugh Jackman Go Claws Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 131, 'title': 'Bianca Belair vs. Jade Cargill'},
{'series': 'Hot Ones', 'season': 0, 'episode': 132, 'title': 'Davante Adams vs. Amon-Ra St. Brown'},
{'series': 'Hot Ones', 'season': 24, 'episode': 11, 'title': 'Vince Vaughn Catches a Hot Streak While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 24, 'episode': 12, 'title': 'Ariana Grande Hits a High Note While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 133, 'title': 'Rob Lowe vs. John Owen Lowe'},
{'series': 'Hot Ones', 'season': 0, 'episode': 134, 'title': "The Umbrella Academy's Tom Hopper vs. Robert Sheehan"},
{'series': 'Hot Ones', 'season': 0, 'episode': 135, 'title': 'Channing Tatum vs. Zoë Kravitz vs. Naomi Ackie'},
{'series': 'Hot Ones', 'season': 0, 'episode': 136, 'title': 'Donald Duck Tries to Keep His Cool While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 137, 'title': 'Beetlejuice goes ghost pepper while eating to die for ribs'},
{'series': 'Hot Ones', 'season': 0, 'episode': 138, 'title': 'Maddie Ziegler vs. Maisy Stella'},
{'series': 'Hot Ones', 'season': 0, 'episode': 139, 'title': 'David Beckham Embraces the Moment While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 140, 'title': 'Kali Uchis vs. JT'},
{'series': 'Hot Ones', 'season': 0, 'episode': 141, 'title': 'Cam Heyward Tackles the Heat For the Hot Ones Football Special'},
{'series': 'Hot Ones', 'season': 0, 'episode': 142, 'title': 'Aubrey Plaza vs. Patti LuPone'},
{'series': 'Hot Ones', 'season': 0, 'episode': 143, 'title': 'Sean Evans Reveals the Season 25 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 25, 'episode': 1, 'title': 'Zlatan Ibrahimović Gets Slide Tackled By Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 2, 'title': 'SZA Bugs Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 3, 'title': 'Jaylen Brown Goes Killer Whale Mode While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 4, 'title': 'Pharrell Williams Sees the Future While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 144, 'title': 'Mackenzie Davis vs. James McAvoy'},
{'series': 'Hot Ones', 'season': 0, 'episode': 145, 'title': 'The ULTIMATE Buffalo Wing Tour! 24 Hours in Buffalo with Camera Guy Bill'},
{'series': 'Hot Ones', 'season': 0, 'episode': 146, 'title': 'Slipknot’s Corey Taylor vs. Shawn “Clown” Crahan'},
{'series': 'Hot Ones', 'season': 25, 'episode': 5, 'title': 'Peter Dinklage Breathes Fire While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 6, 'title': 'Ali Wong Has Beef With Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 7, 'title': 'Jimmy Fallon Gets Spooked By Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 8, 'title': 'ROSÉ Needs a Stress Ball While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 9, 'title': 'Paul Mescal Is a Big Brave Strong Boy While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 25, 'episode': 10, 'title': "Bowen Yang Takes a Hero's Journey While Eating Spicy Wings"},
{'series': 'Hot Ones', 'season': 0, 'episode': 147, 'title': 'Max Greenfield vs. Damon Wayans Jr.'},
{'series': 'Hot Ones', 'season': 0, 'episode': 148, 'title': 'Peter Griffin Bares It All While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 149, 'title': 'How to Make the Ultimate Hot Ones Chicken Wing'},
{'series': 'Hot Ones', 'season': 0, 'episode': 150, 'title': 'Outer Banks: Winner Takes All'},
{'series': 'Hot Ones', 'season': 0, 'episode': 151, 'title': 'Richard Sherman vs. Ryan Fitzpatrick'},
{'series': 'Hot Ones', 'season': 25, 'episode': 11, 'title': 'Demi Moore Celebrates Her Birthday While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 152, 'title': 'T-Pain Regrets His Life Choices While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 153, 'title': 'Hot Ones Thanksgiving Sandwich: 10 LOADED Layers of Leftovers'},
{'series': 'Hot Ones', 'season': 25, 'episode': 12, 'title': 'Ben Stiller Giggles Uncontrollably While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 154, 'title': 'Fred Durst vs. Kyle Mooney'},
{'series': 'Hot Ones', 'season': 26, 'episode': 1, 'title': 'Bad Bunny Risks His Life While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 2, 'title': 'Stavros Halkias Brings His Own Ranch to Eat Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 3, 'title': 'Questlove Refuses Defeat While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 4, 'title': 'Lady Gaga Tries to Keep a Poker Face While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 5, 'title': 'Rob McElhenney Needs to Walk It Out While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 6, 'title': 'Lisa Dances Through the Pain While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 7, 'title': 'Bill Murray Doesn’t Flinch While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 8, 'title': 'Kevin Hart Celebrates 10 Years of Hot Ones While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 9, 'title': 'Selena Gomez and Benny Blanco Burn With Love While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 26, 'episode': 10, 'title': 'Eiza González Cries on Command While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 155, 'title': 'Kyle Kuzma vs. Winnie Harlow'},
{'series': 'Hot Ones', 'season': 0, 'episode': 156, 'title': 'Ken Jeong Spreads Joy at the Hot Ones Holiday Extravaganza'},
{'series': 'Hot Ones', 'season': 0, 'episode': 157, 'title': 'Nicholas Hoult vs. Lily-Rose Depp'},
{'series': 'Hot Ones', 'season': 0, 'episode': 158, 'title': 'The Best Da Bomb Reactions of 2024'},
{'series': 'Hot Ones', 'season': 0, 'episode': 159, 'title': 'How to Make the Ultimate Hot Ones Nachos'},
{'series': 'Hot Ones', 'season': 0, 'episode': 160, 'title': 'Squid Game’s Lee Jung-jae vs. Lee Byung-hun'},
{'series': 'Hot Ones', 'season': 0, 'episode': 161, 'title': 'Lil Yachty Takes His Final Form While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 162, 'title': 'Sean Evans Reveals the Season 26 Hot Sauce Lineup'},
{'series': 'Hot Ones', 'season': 0, 'episode': 163, 'title': 'Keke Palmer vs. SZA vs. Issa Rae'},
{'series': 'Hot Ones', 'season': 0, 'episode': 164, 'title': 'WWE Superstars Drew McIntyre vs. Sheamus'},
{'series': 'Hot Ones', 'season': 0, 'episode': 165, 'title': 'Adam Scott vs. Patricia Arquette'},
{'series': 'Hot Ones', 'season': 0, 'episode': 166, 'title': 'Anthony Mackie vs. Danny Ramirez'},
{'series': 'Hot Ones', 'season': 0, 'episode': 167, 'title': 'Paul Wesley vs. Ian Somerhalder'},
{'series': 'Hot Ones', 'season': 0, 'episode': 168, 'title': 'Doechii vs. DJ Miss Milan'},
{'series': 'Hot Ones', 'season': 0, 'episode': 169, 'title': 'Christina Ricci vs. Melanie Lynskey'},
{'series': 'Hot Ones', 'season': 0, 'episode': 170, 'title': 'Asif Ali vs. Poorna Jagannathan vs. Saagar Shaikh'},
{'series': 'Hot Ones', 'season': 26, 'episode': 11, 'title': 'Saquon Barkley Hurdles Over Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 171, 'title': 'Hailee Steinfeld vs. Michael B. Jordan | Hot Ones Versus'},
{'series': 'Hot Ones', 'season': 26, 'episode': 12, 'title': 'Will Forte Goes For a High Score While Eating Spicy Wings'},
{'series': 'Hot Ones', 'season': 0, 'episode': 172, 'title': 'Kathryn Hahn vs. Seth Rogen'},
{'series': 'Hot Ones', 'season': 0, 'episode': 173, 'title': 'Liv Morgan vs. Dominik Mysterio'},
{'series': 'Hot Ones', 'season': 0, 'episode': 174, 'title': 'Viola Davis vs. Husband Julius Tennon'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 1, 'title': 'Pilot'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 1, 'title': 'Murder Family'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 2, 'title': 'Loo Loo Land'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 3, 'title': 'Spring Broken'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 4, 'title': 'C.H.E.R.U.B'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 5, 'title': 'The Harvest Moon Festival'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 6, 'title': 'Truth Seekers'},
{'series': 'Helluva Boss', 'season': 1, 'episode': 7, 'title': "Ozzie's"},
{'series': 'Helluva Boss', 'season': 2, 'episode': 1, 'title': 'The Circus'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 2, 'title': 'Seeing Stars'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 3, 'title': 'Exes and Oohs'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 4, 'title': 'Western Energy'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 5, 'title': 'Unhappy Campers'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 3, 'title': 'Queen Bee'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 6, 'title': 'Oops'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 7, 'title': 'Look My Way (Music Video)'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 7, 'title': "Mammon's Magnificent Musical Mid-Season Special (ft Fizzarolli)"},
{'series': 'Helluva Boss', 'season': 0, 'episode': 8, 'title': "Hell's Belles"},
{'series': 'Helluva Boss', 'season': 2, 'episode': 8, 'title': 'The Full Moon'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 9, 'title': 'Apology Tour'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 9, 'title': 'Mission: Antarctica'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 10, 'title': 'Mission: Weeaboo-Boo'},
{'series': 'Helluva Boss', 'season': 0, 'episode': 11, 'title': 'Mission: Chupacabras'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 10, 'title': 'Ghostf**kers'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 11, 'title': 'Mastermind'},
{'series': 'Helluva Boss', 'season': 2, 'episode': 12, 'title': 'Sinsmas'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 1, 'title': 'The Layover - Departing Season 3'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 2, 'title': 'The Layover - Departing Season 4'},
{'series': 'Jet Lag: The Game', 'season': 1, 'episode': 1, 'title': 'We Played Connect 4 by Travelling to Actual US States'},
{'series': 'Jet Lag: The Game', 'season': 1, 'episode': 2, 'title': 'The Big Strategy Day'},
{'series': 'Jet Lag: The Game', 'season': 1, 'episode': 3, 'title': 'Finale'},
{'series': 'Jet Lag: The Game', 'season': 2, 'episode': 1, 'title': 'We Did an Actual Race to Circumnavigate the World'},
{'series': 'Jet Lag: The Game', 'season': 2, 'episode': 2, 'title': 'We Need to Get Out of Europe!'},
{'series': 'Jet Lag: The Game', 'season': 2, 'episode': 3, 'title': 'Racing to Asia'},
{'series': 'Jet Lag: The Game', 'season': 2, 'episode': 4, 'title': 'The Race Through Singapore'},
{'series': 'Jet Lag: The Game', 'season': 2, 'episode': 5, 'title': 'The Finale'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 1, 'title': 'We Played Tag Across Europe'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 2, 'title': 'Mistakes Were Made'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 3, 'title': 'Race Through Paris'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 4, 'title': 'The Escape from Paris'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 5, 'title': 'Waffling Through Belgium'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 6, 'title': 'Guten Tag!'},
{'series': 'Jet Lag: The Game', 'season': 3, 'episode': 7, 'title': 'The Finale'},
{'series': 'Jet Lag: The Game', 'season': 4, 'episode': 1, 'title': 'Who Can Get To The Most States In 4 Days'},
{'series': 'Jet Lag: The Game', 'season': 4, 'episode': 2, 'title': 'Battle Initiated'},
{'series': 'Jet Lag: The Game', 'season': 4, 'episode': 3, 'title': 'Challenge: Find the Most Birds'},
{'series': 'Jet Lag: The Game', 'season': 4, 'episode': 4, 'title': 'Find a 4 Leaf Clover'},
{'series': 'Jet Lag: The Game', 'season': 4, 'episode': 5, 'title': 'First to the Grand Canyon Gets Arizona'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 1, 'title': 'We Turned New Zealand into a Giant Real-Life Board Game'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 2, 'title': 'Climb this Mountain?'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 3, 'title': 'We Got Roadblocked'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 4, 'title': 'Episode 4'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 5, 'title': 'Navigate the Jungle Blindfolded'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 6, 'title': 'Who Will Make The First Ferry?'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 7, 'title': 'Complete a Drunk Math Minute'},
{'series': 'Jet Lag: The Game', 'season': 5, 'episode': 8, 'title': 'First to Lookout Point Wins!'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 1, 'title': 'Episode 1'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 2, 'title': 'Episode 2'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 3, 'title': 'Episode 3'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 4, 'title': 'Episode 4'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 5, 'title': 'Episode 5'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 6, 'title': 'Episode 6'},
{'series': 'Jet Lag: The Game', 'season': 6, 'episode': 7, 'title': 'Episode 7'},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 1, 'title': 'TAG EUR*IT 2'},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 2, 'title': 'Full, Delayed, Delayed, Cancelled'},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 3, 'title': 'Disguise'},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 4, 'title': '33 Hours In'},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 5, 'title': "He's Controlled By a Rat?"},
{'series': 'Jet Lag: The Game', 'season': 7, 'episode': 6, 'title': 'Last Chance to Find Him'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 1, 'title': 'Now Leaving Utqiagvik, Alaska'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 2, 'title': '19 Hours In'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 3, 'title': 'Ticket Sales Closed'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 4, 'title': '6H With a Pumpkin'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 5, 'title': 'Steal a Flight?'},
{'series': 'Jet Lag: The Game', 'season': 8, 'episode': 6, 'title': 'Sleeper Train to Victory?'},
{'series': 'Jet Lag: The Game', 'season': 9, 'episode': 1, 'title': 'Episode 1'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 3, 'title': 'The Outtakes - Everything We Cut From Season 8'},
{'series': 'Jet Lag: The Game', 'season': 9, 'episode': 2, 'title': 'Episode 2'},
{'series': 'Jet Lag: The Game', 'season': 9, 'episode': 3, 'title': 'Episode 3'},
{'series': 'Jet Lag: The Game', 'season': 9, 'episode': 4, 'title': 'Episode 4'},
{'series': 'Jet Lag: The Game', 'season': 9, 'episode': 5, 'title': 'Episode 5'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 4, 'title': 'The Outtakes - Everything We Cut From Season 9'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 1, 'title': 'AU$TRALIA'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 2, 'title': 'Wrong Bus'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 3, 'title': 'Memorize 110 Flags'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 4, 'title': 'Last-Minute Ticket?'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 5, 'title': 'Trapped in the Outback'},
{'series': 'Jet Lag: The Game', 'season': 10, 'episode': 6, 'title': 'Final Day'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 5, 'title': 'The Outtakes - Everything We Cut From Season 10'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 1, 'title': 'TAG EUR*IT 3'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 2, 'title': 'Do We Get On This Train?'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 3, 'title': 'Catch Him in the Alps?'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 4, 'title': 'There Goes My Train'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 5, 'title': 'Secret Train Transfer'},
{'series': 'Jet Lag: The Game', 'season': 11, 'episode': 6, 'title': 'One Last Chance to Catch Him'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 6, 'title': 'The Outtakes - Everything We Cut From Season 11'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 1, 'title': 'We Played Hide And Seek Across Japan'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 2, 'title': 'Episode 2'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 3, 'title': 'Episode 3'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 4, 'title': 'Episode 4'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 5, 'title': 'Episode 5'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 6, 'title': 'Episode 6'},
{'series': 'Jet Lag: The Game', 'season': 12, 'episode': 7, 'title': 'Episode 7'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 7, 'title': 'Jet Lag: The Outtakes - Everything We Cut From Season 12'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 1, 'title': 'Episode 1'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 2, 'title': 'Episode 2'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 3, 'title': 'Episode 3'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 4, 'title': 'Episode 4'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 5, 'title': 'Episode 5'},
{'series': 'Jet Lag: The Game', 'season': 13, 'episode': 6, 'title': 'Episode 6'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 8, 'title': 'Hide + Seek Across NYC Episode 1'},
{'series': 'Jet Lag: The Game', 'season': 0, 'episode': 9, 'title': 'Hide + Seek Across NYC Episode 2'},
{'series': 'Jet Lag: The Game', 'season': 14, 'episode': 1, 'title': 'South Korea – TBA'}
]

sonarr_shows = ['Hey Dude', 'All That', 'KaBlam!', "Aaagh! It's the Mr. Hell Show!!!", 'American Dad!', 'American Horror Story', 'American Ninja Warrior', "America's Got Talent", 'BattleBots (2015)', 
                'Bering Sea Gold', 'Big Mouth', 'Black Mirror', "Bob's Burgers", 'Bully Beatdown', 'Celebrity Deathmatch', 'Deadliest Catch', 'Dirty Jobs', 'Downward Dog', 'Dual Survival', 
                "Dude, You're Screwed", "Fast N' Loud: Demolition Theater", 'Futurama', 'Gold Rush', 'Good Game (2017)', 'Hack My Life', 'Halt and Catch Fire', 'Helix', 'How the Earth Was Made',
                  'Howe And Howe Tech', 'Jeff & Some Aliens', 'Jungle Gold', 'Killjoys', 'King of the Hill', 'Kitchen Nightmares (US)', 'Last Week Tonight with John Oliver', 'Man vs. Wild', 
                  "Martha & Snoop's Potluck Dinner Party", "MatPat's Game Lab", 'Metal Hurlant Chronicles', 'Monk', 'Monster Garage', 'Moonshiners', 'Mork & Mindy', 'My Cat From Hell', 'Outer Space Astronauts', 
                  'Outrageous Acts of Science', "Overhaulin'", 'Pawnography', 'Penn & Teller: Bullshit!', 'Penn & Teller: Fool Us', 'Rick and Morty', 'Ridiculousness', 'Room 104', 'seaQuest DSV', 
                  'Showdown of the Unbeatables', 'So You Think You Can Dance', 'Sons of Guns', 'South Park', "Space's Deepest Secrets", 'Stranger Things', 'Street Outlaws', 'Street Outlaws: Memphis', 'Survivor', 
                  'Survivorman', 'The Carbonaro Effect', 'The Keepers', 'The Daily Show', 'The Magicians', 'The Orville', 'The Path', 'The Safecrackers', 'The Simpsons', 'The Tick (2001)', 'The Tick', 
                  'The Tick (2017)', 'The Wil Wheaton Project', 'Top Gear Australia', 'Top Gear (US)', 'Triggers: Weapons That Changed the World', 'True Detective', 'Undergrads', 'Unsolved Mysteries', 'Vikings', 
                  'Viva La Bam', 'Whale Wars', 'What Could Possibly Go Wrong?', 'Whose Line Is It Anyway? (US)', 'Wonder Showzen', 'Worst Cooks in America', 'Zach Stone Is Gonna Be Famous', "Grey's Anatomy", 
                  'Watership Down', 'Jackass', 'Nitro Circus', 'Wildboyz', 'The Dudesons', 'The Dudesons in America', 'Bar Rescue', "Mister Rogers' Neighborhood", 'Street Outlaws: No Prep Kings', 
                  'The Jeselnik Offensive', 'Forged in Fire', 'The Men Who Built America: Frontiersmen', 'Full Metal Jousting', 'Star Trek: Renegades', 'Axanar', 'Star Wars: Ewoks', "Hell's Kitchen (US)", 
                  "Hell's Kitchen (UK)", 'The F Word (US)', 'The F Word', 'Orange County Choppers', 'Joanie Loves Chachi', 'The Fonz and the Happy Days Gang', 'The Osbournes', 'American Chopper', 'Wishbone', 
                  'Clifford the Big Red Dog', 'Foofur', 'Heathcliff', 'Animaniacs', 'Good Eats', 'Mountain Men', 'Neverwhere', 'The Joy of Painting With Bob Ross', 'Outlander', 'Hey Arnold!', 'Russell Howard & Mum',
                  'Russell Howard', 'The Deep', 'The Fall Guy', 'Viper', 'The Ren & Stimpy Show', 'Ren & Stimpy Adult Party Cartoon', 'The Wuzzles', "My Little Pony 'n Friends", 'Friendship is Witchcraft',
                  'Beetlejuice', "You Can't Do That on Television", "Eureeka's Castle", 'Zoobilee Zoo', 'Dungeons & Dragons', 'Tripping the Rift', 'Daria', 'Tiny Toon Adventures', 'Reading Rainbow',
                  'Care Bears: Adventures in Care-A-Lot', 'The Care Bears', 'Care Bears Welcome to Care-a-Lot', 'The Land Before Time', 'Salute Your Shorts', 'David the Gnome', 'Voltron: The Third Dimension',
                  'The Real Adventures of Jonny Quest', 'Dragnet', 'Dragnet (1951)', 'Reno 911!', 'Cash Cab', 'Are You Afraid of the Dark?', 'The Bullwinkle Show', 'Get Smart (1995)', 'Goosebumps', 'Aaahh!!! Real Monsters',
                  'Rugrats', 'Gargoyles', 'Swat Kats: The Radical Squadron', 'Penn & Teller Tell a Lie', 'Alone', 'Comedy Central Roasts', 'The Addams Family', 'The Addams Family (1992)', 'The Addams Family (1973)',
                  'Comedy Central Presents', 'Comedy Central At The Comedy Store', 'Deception With Keith Barry', 'Real Time with Bill Maher', 'SpongeBob SquarePants', 'Inspector Gadget (2015)', "It's Always Sunny in Philadelphia",
                  'Law & Order: Special Victims Unit', 'Law & Order: LA', "The Handmaid's Tale", 'The Fixer', 'She-Ra: Princess of Power', 'Silicon Valley: The Untold Story', 'New Amsterdam', 'The Colbert Report', 'Amazing Earth',
                  'Amazingness', 'Too Stupid to Die', 'The Twilight Zone (1985)', 'Love, Death & Robots', 'The Quon Dynasty', 'How Stuff Works', 'Kimba the White Lion', 'The Boys', 'The Redemption Project with Van Jones',
                  'Planet Earth: The Future', 'Good Omens', 'The Honeymooners', "I'm With Busey", 'The Real Ghostbusters', 'Extreme Ghostbusters', 'For All Mankind', 'Cosmic Disclosure', 'Hazbin Hotel', 'The Mandalorian',
                  'The Maxx', 'The Witcher', "Jasper & Errol's First Time", 'Ozzy & Drix', 'The Wheel of Time', 'Bindi, the Jungle Girl', 'Kid Nation', 'James Randi: Psychic Investigator', 'A Pup Named Scooby-Doo', 'TaleSpin',
                  'Tales of the Gold Monkey', 'Solar Opposites', 'Babylon Berlin', 'Common Knowledge', 'Marsupilami', 'Kids Incorporated', 'Golden Years', 'Gordon Ramsay: Uncharted', 'Harley Quinn',
                  "Sharon, Lois & Bram's Elephant Show", 'Die Hart', 'The Eric Andre Show', 'That Was Us', 'United Shades of America', 'MXC', 'Iron Chef', 'Computer Chronicles', 'Roswell Conspiracies: Aliens, Myths and Legends',
                  'Dune: Prophecy', 'Fargo', 'Wild Ride! with Steve-O', 'The Magic School Bus', 'Resident Alien', 'Droopy', 'The Rachel Maddow Show', 'Lupin', 'Forged With Steele', 'Cop Rock', "America's Funniest Home Videos",
                  'Dynomutt, Dog Wonder', 'Star Trek: Strange New Worlds', 'The Flash Gordon Serials', 'Roger Ramjet', 'Roger and the Rottentrolls', 'Dynamo: Magician Impossible', 'Tales from the Crypt', 'Tales From the Cryptkeeper',
                  'Sealab 2021', 'Sealab 2020', 'Invincible (2021)', 'Muppet Babies', 'The Repair Shop', 'Paranormal Home Inspectors', 'The Sandman', "Clarkson's Farm", 'The Tommyknockers', 'Final Fantasy: Legend of the Crystals',
                  'Only Fools and Horses', 'You', 'BattleBots', 'American Gladiators (2008)', 'The Bob Newhart Show', 'Coach', 'The Critic', 'Squid Game', 'The Corner', 'Getting Doug with High', 'Foundation (2021)', 'The Soup',
                  'Web Soup', 'The Soup Investigates', 'Star Wars: Visions', '60 Minutes', 'Sesame Street', 'My Wild Backyard', 'Moomin', 'Patriot Games', 'Peacemaker', 'Go-Big Show', 'Euphoria (US)', 'Smiling Friends', 
                  'The Legend of Vox Machina', 'Fraggle Rock (UK)', 'Fraggle Rock: The Animated Series', 'Under the Umbrella Tree', 'Cow and Chicken', 'Death Note (2015)', 'Death Note: New Generation', 'Street Genius', 
                  'Hot Ones: The Game Show', 'Family Guy', 'The New York Times Presents', 'The Last of Us', 'NewsRadio', 'My Next Guest Needs No Introduction With David Letterman', 'The Terminal List', 'Dead Famous DNA', 
                  'Severance', "Don't Hug Me I'm Scared", 'The New Dick Van Dyke Show', 'The Carol Burnett Show', 'Carol Burnett and Friends', 'The Ed Sullivan Show', 'Muppetisms', 'Muppets Tonight', 'House of the Dragon', 
                  'This Old House', 'Ask This Old House', 'The New Yankee Workshop', 'Wood Works', 'Remington Steele', 'Son of a Dungeon', 'Welcome to Wrexham', 'Princesses', 'Lassie', 'Andor', 'Interview with the Vampire', 
                  'Recess', "Dexter's Laboratory", 'Darkwing Duck', 'The Plucky Duck Show', 'The Legend of Zelda', "America's Test Kitchen", "Hunger Pangs by America's Test Kitchen", '60 Days In', 'The Marvel Super Heroes', 
                  'Table Flip', 'Megamind Rules!', 'Robot Wars', 'Wednesday', 'Sagwa, the Chinese Siamese Cat', 'Courageous Cat and Minute Mouse', 'Eek! the Cat', 'Eerie, Indiana', 'Simsala Grimm', 'Xena: Warrior Princess', 
                  'Barmageddon (2022)', 'Kaleidoscope (2023)', 'Anne Rice’s Mayfair Witches', 'The Ark', 'The Jon Stewart Show', 'The Bear', 'The Adventures of Super Mario Bros. 3', 'Super Mario World', 
                  'The Super Mario Bros. Super Show!', 'The Adventures of the Super Mario Brothers', "Mike Judge's Beavis and Butt-Head", 'Jet Lag: The Game', 'Helluva Boss', 'Top Gear (1978)', 'Beyond Belief: Fact or Fiction', 
                  "Ripley's Believe It or Not! (1982)", "Ripley's Believe It or Not! (2000)", 'Other Space', 'Citadel', "Mark Rober's Revengineers", 'Kaguya-sama: Love Is War Mini', 'Shrinking', 'The Shining', 
                  'Extraordinary Birder with Christian Cooper', 'Bluey (2018)', 'Leverage: Redemption', 'Martin Yan: Quick & Easy', "Martin Yan's Hidden China", "Martin Yan's Taste of Vietnam", "Martin Yan's Asian Favorites", 
                  'The Adventures of Jimmy Neutron: Boy Genius', 'Doogie Howser, M.D.', 'The Two Ronnies', 'The Graham Norton Show', 'QI', 'The Mighty Boosh', 'Thunderbirds', 'Puppets Who Kill', 'Prehistoric Planet',
                  'Rats on Cocaine', 'Gordon Ramsay on Cocaine', 'Barefoot Contessa', 'Diners, Drive-ins and Dives', 'Space Ghost', 'Space Ghost and Dino Boy', 'Twisted Metal', 'Tremors', 'The Rookie', 'Hot Ones', 
                  'My Little Pony: Equestria Girls', 'My Little Pony: Meet the Ponies', 'Teen Titans Go!', 'Ahsoka', 'Call the Midwife', '+Tic Elder Sister', 'After War Gundam X', 'BEASTARS', 'Bleach', 
                  'Boruto: Naruto Next Generations', 'Corpse Party: Tortured Souls', 'Crying Freeman', 'Digimon: Digital Monsters', 'Digimon Adventure 20th Memorial Story', 'Digimon Adventure tri.', 'Digimon Frontier', 
                  'Digimon Fusion', 'Digimon Tamers', 'Dororo', 'Dr.STONE', 'Fate/Stay Night: Unlimited Blade Works', 'Fruits Basket', 'Gingitsune: Messenger Fox of the Gods', 'Grenadier', 'Grimgar of Fantasy and Ash', 
                  'Hellsing', 'Hellsing Ultimate Abridged', 'Hikaru no Go', 'Hitori No Shita: The Outcast', 'Hunter x Hunter', "JoJo's Bizarre Adventure", "JoJo's Bizarre Adventure (2012)", 'Jujutsu Kaisen', 'Kaiji', 
                  'Kakegurui Twin (2022)', 'Kurokami The Animation', 'Legends of the Dark King: A Fist of the North Star Story', 'LEGO Monkie Kid', 'Lupin the Third: The Woman Called Fujiko Mine', 'Magi: Adventure of Sinbad', 
                  'Megazone 23', 'Mobile Fighter G Gundam', 'Mobile Suit Gundam', 'Mobile Suit Gundam: MS IGLOO', 'Mobile Suit Gundam 00', 'Mobile Suit Gundam AGE', 'Mobile Suit Gundam SEED', 'Mobile Suit Gundam SEED Destiny', 
                  'Mobile Suit Gundam: The 08th MS Team', 'Mobile Suit Gundam Wing', 'Mobile Suit Gundam ZZ', 'Mobile Suit Victory Gundam', 'Monster', 'My Hero Academia', 'Naruto', 'Naruto Shippuden', 'One Piece', 
                  'Paranoia Agent', 'Phantom: Requiem for the Phantom', 'Pokémon: The Two Professors', 'Pokémon Chronicles', 'Pokémon Concierge', 'Pokémon Evolutions', 'Pokémon Mystery Dungeon', 'Princess Tutu', 'Raruto', 
                  'Record of Ragnarok', 'Re: ZERO, Starting Life in Another World', 'Ring Warriors', 'Sabagebu! - Survival Game Club! -', 'Sailor Moon', 'S-CRY-Ed', 'SD Gundam Force', 'Star Blazers', 'Star Blazers 2199', 
                  'Super HxEros', 'The Rising of the Shield Hero', 'TRIGUN STAMPEDE', 'Turn A Gundam', 'Vinland Saga', 'Vision of Escaflowne', 'Pokémon', 'Jimeoin', 'Rurouni Kenshin', 'ONE PIECE (2023)', 'Rurouni Kenshin (2023)', 
                  'The Masked Singer (US)', 'Running Man', 'Adventure Time: Fionna & Cake', 'Disjointed', 'Saturday Night Live', 'Dinosaurs', 'The Ropers', 'The Warwick Rowers', 'Strawberry Shortcake (1980)', "Three's a Crowd", 
                  'Three Sheets', 'Gen V', 'Robot Wars Extreme', 'Robot Wars: Extreme Warriors', 'Mobile Suit Gundam: The Witch from Mercury', 'Tornado Chasers', 'The Walking Dead: Dead City', 'The Walking Dead: Daryl Dixon', 
                  'Sledge Hammer!', 'The Amazing Digital Circus', 'Murder Drones', 'Blue Eye Samurai', 'Together We Stand', 'Love Is Blind', 'Freakazoid!', 'Captain N: The Game Master', 'BEEF', 'Off the Air', 'Æon Flux', 
                  'The Night Agent', 'Felix The Cat', 'The Prison Confessions of Gypsy Rose Blanchard', "Gypsy's Revenge", 'The Adventures of Sam & Max: Freelance Police', 'The Amanda Show', 'Mountain Men Alaska', 
                  'Mr. & Mrs. Smith (2024)', 'After Midnight', 'Alice in Wonderland (1985)', 'Blazing Dragons', 'The Phil Silvers Show', 'F Troop', 'Oswald the Lucky Rabbit', 'The Best of Roger Rabbit', 'Destroy Build Destroy', 
                  'NFL Super Bowls', 'Mythic Quest', 'The Littles', 'Home Movies', 'Avatar: The Last Airbender (2024)', 'Would I Lie to You?', 'Grimsburg', 'Heathcliff and the Catillac Cats', 
                  'I Think You Should Leave with Tim Robinson', 'Utopia (AU)', 'Hee Haw', 'The Gong Show', 'Who Wants to Be a Millionaire?', 'Deal or No Deal', 'The Hollywood Squares', 'The New Hollywood Squares', 
                  'Hollywood Squares', 'That Time I Got Reincarnated as a Slime', 'That Time I Got Reincarnated as a Slime: Visions of Coleus', '3 Body Problem', "X-Men '97", 'X-Men: The Animated Series', 'VR Troopers', 
                  'Roughnecks: The Starship Troopers Chronicles', 'The Conners', 'Josie and the Pussycats', 'Top Cat', 'Hanna-Barbera Superstars 10', 'The Hanna-Barbera Happy Hour', 'Jabberjaw', 
                  'Hanna-Barbera Educational Filmstrips', 'Wacky Races', 'Hong Kong Phooey', 'Aquaman (1967)', 'Wildfire', 'Dastardly & Muttley in Their Flying Machines', "Scooby's All Star Laff-A-Lympics", 'The Thing', 
                  'The Huckleberry Hound Show', 'Godzilla', 'Quick Draw McGraw', 'The Ruff and Reddy Show', 'The Peter Potamus Show', 'The Patrick Star Show', 'Atom Ant', 'Spider-Man', 'Birdman and the Galaxy Trio', 
                  "Wild Burma: Nature's Lost Kingdom", 'Fantastic Four (1967)', 'Fantastic Four', 'Fantastic Voyage', 'The New Adventures of Huckleberry Finn', 'Shogun', 'Shōgun', 'Fallout', 'A Squirrel and a Hedgehog', 
                  "Conan O'Brien Must Go", 'The Spiderwick Chronicles', 'Three-Body', 'The Three-Body Problem', 'Melancholia', 'Delicious in Dungeon', 'Make Some Noise', 'My Feet are Killing Me', 'Dark Matter (2024)', 
                  'NOVA', 'Dimension 20', 'The Opposition with Jordan Klepper', 'Based On A True Story', 'Blark and Son', 'NCIS', 'Game Changer', 'Smartypants', 'What a Cartoon', 'Krypto the Superdog', 'Craig of the Creek', 
                  'Secret Level', 'Total Blackout (US)', 'Total Blackout', 'Mr. Show', 'Chowder', 'Rick and Morty: The Anime', 'Only Murders in the Building', "Herman's Head", 'The Machines That Built America: Snack Sized', 
                  'The Food That Built America', 'The Icons That Built America', 'The Mega-Brands That Built America', 'The Toys That Built America: Snack Sized', 'The Lord of the Rings: The Rings of Power', 'Gerbert', 
                  'Fraggle Rock: Back to the Rock', 'Rooted', 'Roots', 'Criminal Minds', 'Neurotically Yours Foamy the Squirrel Reboot', 'Mind Your Language', '3-2-1 Contact', '3-2-1 Contact Extra', '3-2-1 Classroom Contact', 
                  '9-1-1', "Frieren: Beyond Journey's End", 'Brassic', 'Ouran High School Host Club', 'Wizards Beyond Waverly Place', 'Heartstopper', 'DAN DA DAN', 'All Creatures Great and Small', 
                  'All Creatures Great & Small (2020)', "Terry Pratchett's Hogfather", "Terry Pratchett's Truckers", "Terry Pratchett's Soul Music", "Terry Pratchett's Wyrd Sisters", "Terry Pratchett's The Colour of Magic", 
                  'Creature Commandos', 'Only Connect', 'Silo', 'Human vs Hamster', 'Star Wars: Skeleton Crew', 'Tiny Toons Looniversity', 'Beast Games', 'Interior Chinatown', 'Waterloo Road', 'Bluey Minisodes', 
                  'Space Runaway Ideon', 'Abbott Elementary', 'Sakamoto Days', 'RWBY', "A Real Bug's Life", 'Miracle Workers (2019)', 'A Man on the Inside', 'Paradise (2025)', 'Majikoi Oh! Samurai Girls!', 
                  'Ninja Girl & Samurai Master', 'Samurai Girls', "Gilligan's Planet", 'Loudermilk', 'Deli Boys', 'Dexter: Original Sin', 'Stoner Cats', 'Mo (2022)', 'The Get Along Gang', 'The White Lotus', 
                  'The Joe Schmo Show', 'Sirens (2014)', 'Common Side Effects', 'Vice Principals', 'Daredevil: Born Again', 'The Blacklist', 'Landman', 'Animal Control', 'No Taste Like Home with Antoni Porowski', 
                  'Tasting History with Max Miller', 'Swimming with Sharks', 'Vikings: Valhalla', 'Nobody Wants This', 'Star Trek: The Animated Series', 'SAS Rogue Heroes', 'The Gifted', '61st Street', 'Family Law (2021)', 
                  'The Good Wife', 'Goliath', 'The Good Fight', 'Upload', 'Tyler Perry’s Zatima', 'The Last Days of Ptolemy Grey', 'Reacher', 'Lessons in Chemistry', 'Chicago Fire', 'Tacoma FD', 'After the Rain', 
                  'Devilman Crybaby', 'The Pitt', 'Mike Tyson Mysteries', 'Poker Face (2023)', 'Distractible']


if __name__ == "__main__":
    for title in titles:
        result = match_title_to_sonarr_show(title, sonarr_shows)
        print(f"\nMatched: {result['input']}")
        print(f"→ Series: {result['matched_show']}")
        print(f"→ Score: {result['score']}")
        print(f"→ Why: {result['reason']}")


    # print("\n\n\n\n\n")

    # for title in titles:
    #     result = match_title_to_sonarr_episode(title, sonarr_data)
    #     print(f"\nMatched: {result['input']}")
    #     print(f"→ Series: {result['matched_show']}")
    #     print(f"→ Season {result['season']} Episode {result['episode']}: {result['episode_title']}")
    #     print(f"→ Score: {result['score']}")
    #     print(f"→ Why: {result['reason']}")
